# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e532daeef23cf0e9f3cf07963cfb6a513865367c53636e1d0470f76aa71583d01a51e608e1fca4142a7b24f7b6bc1620a73789efc6c624cf6c2fca3095786682

test:
  secret_key_base: 0628fb739f57f899b6e8eb0733b77b4ca9070da72ba1b6b920efcdb94404bd2ab83d769e80d926f3864d9350f161ad9836621f3a135e809ff847ab611dafde04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
